name-template: "EasyCord v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "New Plugins"
    labels: [plugin, feature]
  - title: "Features"
    labels: [enhancement]
  - title: "Bug Fixes"
    labels: [bug, fix]
  - title: "Security"
    labels: [security]
  - title: "Dependencies"
    labels: [dependencies]
  - title: "Tests"
    labels: [test, tests]
  - title: "Documentation"
    labels: [documentation, docs]

version-resolver:
  major:
    labels: [breaking-change]
  minor:
    labels: [feature, plugin, enhancement]
  patch:
    labels: [bug, fix, security, dependencies, test, documentation]
  default: patch

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: $PREVIOUS_TAG...v$RESOLVED_VERSION
